version: '3'
services:
  api:
    build: ./app
    command: yarn start
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bandsongs
      POSTGRES_PASSWORD: test
      POSTGRES_DB: bandsongs

volumes:
    db_data:
